import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import LenisLayout from "@/components/ui/layout/LenisLayout";
import QueryLayout from "@/components/ui/layout/QueryLayout";
import ContextLayout from "@/components/ui/layout/ContextLayout";

const jakartaSans = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jakartaSans.variable} bg-neutral-50`}>
        <LenisLayout>
          <QueryLayout>
            <ContextLayout>{children}</ContextLayout>
          </QueryLayout>
        </LenisLayout>
      </body>
    </html>
  );
}
